### ISSUE TITLE
Allow validation for projects with POM packaging

### ISSUE THREAD

**Issue by camshoff** [basepom/duplicate-finder-maven-plugin#11]
When building EAR files, we usually do not use EAR packaging, but a packaging of POM and configure various plugins to build the deployment files. Nevertheless, we'd like to run duplicate-finder plugin at this point, because it's at the end of the build chain.

Unfortunately, the plugin does not work on such projects, issuing a message:
Ignoring POM project!

This was not the case for maven-duplicate-finder-plugin. Please find a way to run the plugin on POM style projects, too -- for instance by forcing it with some config option.

**Comment by hgschmie** [comment]
This is a good idea. Will add a switch to allow checking POM projects.

**Comment by hgschmie** [comment]
Should be fixed with 4810f25a84c17c028260aa979c2ddf518d224d08, will be in 1.2.0 release.

**Comment by camshoff** [comment]
This is great news... Thanks!
