### ISSUE TITLE
Project will not build without JAVA7_HOME environment variable set

### ISSUE THREAD

**Issue by mbellomo** [basepom/duplicate-finder-maven-plugin#18]
This project will not build without JAVA7_HOME environment variable set.  That's not a very common environment variable to be set.  JAVA_HOME is reasonable, but variations of this seems unusual.

**Comment by stevenschlansker** [comment]
This is so that you can correctly compile the plugin to target Java 7 from a machine that has Java 8 installed.

It is probably better to adopt the Maven `toolchains.xml` approach, similarly to https://github.com/jdbi/jdbi/pull/169
