### ISSUE TITLE
Wiki: Description of option 'failBuildInCaseOfConflict' wrong?

### ISSUE THREAD

**Issue by oldzitterhand** [basepom/duplicate-finder-maven-plugin#26]
Hi,

sorry to open an issue for that, but I could not figure out how to contact you guys.

I think the description of the option '**failBuildInCaseOfConflict**' might be wrong/misleading as it is the same text as for the option '**failBuildInCaseOfDifferentContentConflict**':
_'Fail the build if any class or resource on the classpath is duplicate and their SHA256 hash is different.'_

Shouldn't it read something like this?
_'Fail the build if any class or resource on the classpath is duplicate regardless of the SHA256 hash values.'_

See:
https://github.com/basepom/duplicate-finder-maven-plugin/wiki/Simple%20Options

Cheers
Patrick

**Comment by hgschmie** [comment]
Thank you for opening this as an issue a long time ago. I actually updated the docs today. :-)
