### ISSUE TITLE
Does the plugin work with Kotlin?

### ISSUE THREAD

**Issue by piyushmor** [basepom/duplicate-finder-maven-plugin#48]
I have a Kotlin class where I have multiple methods with the same name but different arguments in a single kotlin file (not class). The plugin says its having duplicates but actually not exists

**Comment by hgschmie** [comment]
that is a great question. I have not actually tried it. Do you have an example kotlin file that I can test with?

**Comment by piyushmor** [comment]
there is no need for that.. it was a duplicate in library

**Comment by hgschmie** [comment]
:-) So the plugin did its job.
