### ISSUE TITLE
Replace/remove slf4j-log4j12

### ISSUE THREAD

**Issue by xandris** [basepom/duplicate-finder-maven-plugin#53]
We have automated tools to scan for and flag log4j 1.x. The rationale for the scan is that 1.x was EOL a while ago. I can't speak to the validity of that premise, and maybe I could fight that battle in my organization, but I figured it would be worth asking if this plugin can depend on a newer or different logging framework.

**Comment by hgschmie** [comment]
Hi Alexandra,

Thank you for flagging this. I will look into replacing the logging dependency.

**Comment by hgschmie** [comment]
Release 1.5.1 which fixes this issue ( no longer uses log4j)
